### ISSUE TITLE
Can't get working with LibreSonic

### ISSUE THREAD

**Issue by weirdcrap** [midwan/MB_SubSonic#20] opened 2017-01-11 20:53 UTC
Just found out about MusicBee and have a LibreSonic server so I figured I would check out your plugin. I am using LibreSonic 6.1, MusicBee v3, and v2.9 of your plugin. Has this been tested/known to work with LibreSonic?

I am having issues getting the plugin connected to LibreSonic either through the domain name or the direct static IP address, I just keep getting an error that the server did not respond in an expected way (plugin did not got OK from server).

I can see that at least some information is getting up to the server as I have a new player entry in LibreSonic  (though it isn't properly identified) and I am the only person using the server so I know the new player came from me.

**Comment by weirdcrap** [comment] 2017-01-12 19:23
@midwan Sure.

This is running in a docker container made by the lovely folks at [LinuxServer.io](https://hub.docker.com/r/linuxserver/libresonic/) which is in turn running on top of [UnRAID 6.3-RC6](https://lime-technology.com/) (which IIRC is essentially a custom build of slackware).

When navigating to my server using the ping documentation you linked I get this back:

`<subsonic-response xmlns="http://libresonic.org/restapi" status="failed" version="1.13.0">
<error code="10" message="Required parameter is missing."/>
</subsonic-response>`

I have tried both Token (first) and Hex Encoded (second) and neither appears to work correctly, I just get the same failure message I mentioned above.

**Comment by midwan** [comment] 2017-01-13 12:40
@weirdcrap 
Yes, it definitely because it doesn't get a Ping response. As documented in the Subsonic API, it should come back with an empty <subsonic-response> with a status of "ok". Yours comes back with "failed" mentioning that "required parameter is missing", which seems a bit strange. Normally for a Ping call there is no extra parameters needed, at least according to the official API specs (as linked above).

Is there a chance the LibreSonic API has a difference there? I'll have to check.

I'll setup a similar environment to test it out, unless you come up with anything from your side until then. ;)

**Comment by weirdcrap** [comment] 2017-01-19 14:47
Interesting, the author of Libresonic claims he attmpts to keep Libresonic cross compatible with Subsonic applications where possible so I am surprised he doesn't have the ping function in the API.

Is there anything you would like from me to help you troubleshoot?

**Comment by midwan** [comment] 2017-01-19 20:41
@weirdcrap 
Not for now, I'm thinking of implementing a "fallback" check for such cases where Ping fails, that would allow LibreSonic to work also. Once that's in place, I'll notify you here so you can test!

**Comment by midwan** [comment] 2017-02-01 19:51
Note to self: Maybe a checkbox (something like "Test connection") to control if a Ping command is sent to the server to validate the connection. It should be checked by default, but if disabled we could skip the Ping command altogether and assume the server is there.

**Comment by midwan** [comment] 2017-02-01 19:54
@weirdcrap 
I just managed to recreate this on a standard Subsonic installation also, which does normally have Ping.view available.

I'll work on a fix in the plugin code and let you know.

**Comment by midwan** [comment] 2017-02-01 19:57
@weirdcrap 
Update: could you please test the following instead:
http://your-server/rest/ping.view?u=joe&p=sesame&v=1.12.0&c=myapp

where "joe" is a valid username, and "sesame" is a valid password for your server?

**Comment by weirdcrap** [comment] 2017-02-02 20:23
Absolutely, I will test it tonight when I get home from work.

**Comment by weirdcrap** [comment] 2017-02-02 22:51
@midwan looks like we are good, right?

`<subsonic-response xmlns="http://libresonic.org/restapi" status="ok" version="1.13.0">
<script data-x-lastpass="">
(function(){var c=0;if("undefined"!==typeof CustomEvent&&"function"===typeof window.dispatchEvent){var a=function(a){try{if("object"===typeof a&&(a=JSON.stringify(a)),"string"===typeof a)return window.dispatchEvent(new CustomEvent("lprequeststart",{detail:{data:a,requestID:++c}})),c}catch(f){}},b=function(a){try{window.dispatchEvent(new CustomEvent("lprequestend",{detail:a}))}catch(f){}};"undefined"!==typeof XMLHttpRequest&&XMLHttpRequest.prototype&&XMLHttpRequest.prototype.send&&(XMLHttpRequest.prototype.send= function(c){return function(f){var d=this,e=a(f);e&&d.addEventListener("loadend",function(){b({requestID:e,statusCode:d.status})});return c.apply(d,arguments)}}(XMLHttpRequest.prototype.send));"function"===typeof fetch&&(fetch=function(c){return function(f,d){var e=a(d),g=c.apply(this,arguments);if(e){var h=function(a){b({requestID:e,statusCode:a&&a.status})};g.then(h)["catch"](h)}return g}}(fetch))}})(); (function(){if("undefined"!==typeof CustomEvent){var c=function(a){if(a.lpsubmit)return a;var b=function(){try{this.dispatchEvent(new CustomEvent("lpsubmit"))}catch(k){}return a.apply(this,arguments)};b.lpsubmit=!0;return b};window.addEventListener("DOMContentLoaded",function(){if(document&&document.forms&&0<document.forms.length)for(var a=0;a<document.forms.length;++a)document.forms[a].submit=c(document.forms[a].submit)},!0);document.createElement=function(a){return function(){var b=a.apply(this, arguments);b&&"FORM"===b.nodeName&&b.submit&&(b.submit=c(b.submit));return b}}(document.createElement)}})();
</script>
</subsonic-response>`

**Comment by weirdcrap** [comment] 2017-02-02 22:54
@midwan <subsonic-response xmlns="http://libresonic.org/restapi" status="ok" version="1.13.0">

**Comment by midwan** [comment] 2017-02-03 14:37
@weirdcrap 
Thanks for that. It confirms my suspicion that it only works with authentication passed in but for some reason, it didn't work correctly earlier for you.

Could you please try with the latest released version (v2.9 currently) and see if that helps?
Make sure to test both the default Token Based authentication and Hex Encoded Password methods, in case one does not work and the other does...

**Comment by weirdcrap** [comment] 2017-02-06 15:48
I still get the error that "the subsonic server did not respond in a way the plugin expected. Apply settings anyway?" regardless of which authentication method I attempt to use. Do I need to pass the rest api path to the plugin? Currently my settings are:
hostname: libresonic.mydomain.com   Port: 80
Path: /
username: musicbee
password: *********************

I forgot to mention in the OP that I originally tried this through an nginx reverse proxy I have setup though I also tried a direct connection using my static ip and application port and it doesn't seem to make a difference.

I can set you up a test user if you want to check things out for yourself.

**Comment by midwan** [comment] 2017-02-06 16:39
Could you please set up a temp account for me to test with?

Kindly send the details at midwan at Gmail dot com.

**Comment by weirdcrap** [comment] 2017-02-06 17:33
Credentials sent.

**Comment by midwan** [comment] 2017-02-06 21:15
@weirdcrap 
Thank you, I managed to recreate the problem with the account you gave me.
The problem is due to the XML format of the response, and specifically while attempting to Deserialize it.

Since the plugin expects a Subsonic API response according to the documentation (see here: http://www.subsonic.org/pages/api.jsp#ping), it expects that the response will have the Root element named "subsonic-response". Instead of that however, LibreSonic returns "libresonic-response" as the Root element and the code does not know how to Deserialize that.

This is really a bug of LibreSonic, if they want to be 100% compatible with SubSonic they need to stick to the same API responses. There might be a way to have a workaround on the plugin, but it will require some effort. I'll see if I can come up with an idea about it...

**Comment by midwan** [comment] 2017-02-06 21:17
@weirdcrap 
From what I can see they have a related issue at LibreSonic's project page also: https://github.com/Libresonic/libresonic/issues/82

**Comment by weirdcrap** [comment] 2017-02-06 21:22
Thanks for your hard work, glad to know it wasn't just something I was doing wrong.

I will keep an eye on this thread and the one over at Libresonic and hopefully a fix isn't to far down the line. It sounds like they made those changes to differentiate themselves legally from the SubSonic project https://github.com/Libresonic/libresonic/issues/52

**Comment by midwan** [comment] 2017-02-06 21:25
@weirdcrap 
Yes, and from what I can see they reverted them because it caused several clients to stop working (e.g. DSub), so the current version they have on the repo is using the "subsonic-response". Try upgrading to that and test again, it should work... :)

Meanwhile I'll look into adding libresonic as an alternative.

**Comment by weirdcrap** [comment] 2017-02-06 21:27
From what I can see I am using the latest version of LibreSonic available. The Repo lists v6.1 as the latest release and my server is also running on 6.1.
![image](https://cloud.githubusercontent.com/assets/22824785/22667072/bebe8322-ec80-11e6-87ff-6e35ad246599.png)

**Comment by weirdcrap** [comment] 2017-02-06 21:28
I could try deleting and re-pulling the docker container.

**Comment by midwan** [comment] 2017-02-06 21:28
Hm, maybe they haven't published this version with the fix? Although it was from last May...

**Comment by weirdcrap** [comment] 2017-02-06 21:32
I am no expert in GitHub but it looks like it isn't in the stable branch?
https://github.com/Libresonic/libresonic/blob/stable/libresonic-main/src/main/java/org/libresonic/player/controller/JAXBWriter.java#L137

**Comment by midwan** [comment] 2017-02-06 21:33
The latest release (https://github.com/Libresonic/libresonic/releases) contains the fix, at least in the source files that I just checked...

**Comment by weirdcrap** [comment] 2017-02-06 21:34
Ok, I will delete and recreate the docker and report back.

**Comment by weirdcrap** [comment] 2017-02-06 21:39
Ok, re-creating the docker container didn't fix it. Maybe the LinuxServer.io container is pulling from an older copy of the source? I won't pretend to know how docker, containers, github, and all that stuff mesh together lol.

I see this in the Versions history at the bottom of the [container](https://hub.docker.com/r/linuxserver/libresonic/) page:
"29.11.16: Switch to building from release tags following v6.1 stable release."

**Comment by weirdcrap** [comment] 2017-02-06 22:02
Doesn't seem to matter which docker container template I choose, all of them have issues with the plugin.

**Comment by midwan** [comment] 2017-02-06 22:06
It seems that the problem is not only the XmlRootAttribute, which is fixed in these versions of LibreSonic, but also the Namespace which indicates "http://libresonic.org/restapi" instead of the expected "http://subsonic.org/restapi". I didn't notice that earlier, sorry.

These are attributes in the XML response and they are expected with that exact naming from the receiving end to identify what it got (and how to parse it and make sense out of it). If the naming is different, then it's not recognized and cannot be Deserialized - hence the error message.

Let me see if I an figure out a better way to handle this...

**Comment by midwan** [comment] 2017-02-06 23:01
@weirdcrap 
OK, I have a fix implemented and it seems to work. I'll prepare a beta binary for you to test with shortly...

**Closed** 2017-02-06 23:05 UTC
Labels: enhancement

**Comment by midwan** [comment] 2017-02-06 23:10
@weirdcrap 
You can find version v2.10 beta in the Releases (https://github.com/midwan/MB_SubSonic/releases) section, please give it a try and let me know how it works for you.

**Comment by weirdcrap** [comment] 2017-02-07 14:24
Works great! Thanks for your hard work. It works with my reverse proxy setup and both Hex Enc and Token authentication are working.

**Comment by midwan** [comment] 2017-02-07 17:51
Thanks for confirming!

**Comment by midwan** [comment] 2022-05-08 18:24
@weirdcrap Is anyone still using Libresonic these days?
It seems like people moved to Airsonic and from there to Airsonic-advanced now. I'm considering removing support for it, as the project seems dead for a few years now.
