### ISSUE TITLE
Error retrieving response from Subsonic server

### ISSUE THREAD

**Issue by andocromn** [midwan/MB_SubSonic#22] opened 2017-02-08 20:10 UTC
I am getting an error message with 2.9, also tried 2.8 but had different issue where it would skip tracks
the error message box reads as below however this is no log file created
This doesn't seem to be during any action in particular, it just pops up while playing and continues playing normally

Error retrieving response from Subsonic server:
System.Net.WebException: The operation timed out 
    at System.Net.HttpWebRequest.GetResponse()
    at RestSharp.Http.GetRawResponse(HttpWebRequest request)
    at RestSharp.Http.GetResponse(HttpWebRequest request)

thanks

**Comment by midwan** [comment] 2017-02-15 20:46
@andocromn 
Sorry for the delay... :)

Strange messages, something is timing out in the background. Is it still scanning the collection from the server? There is a background thread doing that and it will continue until it's done, building the local cache. 

Have you tried waiting a bit for the process to complete, or at least have time to cache more? Maybe that will show a different behavior.

**Comment by andocromn** [comment] 2017-02-16 19:38
i had not considered cache building.  is there a way i can if it's still doing that?

most recently i have issues where anything i drag into the play queue will not play, but if do 'Play now' it works.  heres this most recent error

`2/16/2017 2:34:10 PM - 10.0.14393.0 - 3.0.6132.15853 - url: Subsonic:\De La Tierra/2016 - II/De La Tierra - 04 - Fome.mp3\De La Tierra\2016 - II\De La Tierra - 04 - Fome.mp3
System.IO.FileNotFoundException: Unable to find the specified file.
   at #=qL2UZEcvMrPitgReDO3HbSgdypFfX_8TMfrXivfOsZtI=.#=qGQC_2o9Q5sZ9bkzuAKP65w==(#=qZsbih$YwvJ5OgcdcG81xQg== #=qJUxXiyd3fKZJQzTV3u9E1Q==, #=qI_C_6$a81pAebbaYnO7VwtLwgieay75o4_nnJJNNjuc= #=qWNEajmyquudIW8ofKsTsYw==, Boolean #=qfXs3HYh95yMKW4A03MtoNw==, Boolean #=qYs2Z6UwWi2c8xan9u90i7Q==, Boolean #=qW_1SBa15KDNcwqSjJ8CjkKy0xdpWGG4_icDEloyt0YA=, Boolean #=qx3l6wHqqNyxPLhx6yQ9A7g==, Int32 #=qdVu9os5zbCfLiiWxwl9Wf26fSqcmhm8bAdrWpZC7RoI=)
   at #=qL2UZEcvMrPitgReDO3HbSgdypFfX_8TMfrXivfOsZtI=.#=qbfludmPPl53g5kMHMTqovQ==(Object #=qsM$WObGdzVdE22zJ22ekag==)

`

**Comment by midwan** [comment] 2017-02-27 10:45
@andocromn 
The issue with dragging in the play queue is now handled separately (#23), so let's stick to the original one here.

Do you still get it?

**Comment by midwan** [comment] 2017-02-27 12:14
@andocromn 
I'm pushing out an update which will display a status update on what the plugin is working on (if anything) on the MusicBee status bar. That should make it easier to see if it's busy doing something or not. ;)

**Comment by midwan** [comment] 2017-04-12 21:21
@andocromn 
I've pushed out a new release that includes the status bar messages, so you can easily see if there's any activity going on.

Please let me know if you still have problems with this version, otherwise we can close this issue.

**Comment by andocromn** [comment] 2017-04-13 17:38
@midwan I don't see the new release... latest I see is v2.11 on Feb 28 which I am using.  Also, do you recommend upgrading to MusicBee 3.0.6276 released on March 10?

Thanks

**Comment by midwan** [comment] 2017-04-13 18:39
@andocromn 
Yes, although I published the binary just yesterday, there hasn't been any code changes since Feb 28.
And I always recommend upgrading to the latest MB version, as Steven fixes bugs in updates (some of which are bugs I've reported). ;)

**Comment by midwan** [comment] 2017-04-18 22:25
@andocromn 
Did you get a chance to test this out with the latest version?
Any progress regarding this issue please?

**Comment by andocromn** [comment] 2017-04-19 19:16
@midwan I have been using the 2.11 version.  I was ready to say the problem was resolved, however it just popped up again.  same message, however I am now wondering if the timeout is really just an HTTP timeout.  I don't see any way of changing the timeout value in musicbee though

**Comment by midwan** [comment] 2017-04-19 19:59
@andocromn 
There isn't such an option available from the interface, since I never thought the value would need to be changed.

I could compile a version with an increased timeout value to see if that helps in your situation, if you'd like?

**Comment by andocromn** [comment] 2017-04-20 17:43
yeah, i could try that if you can compile it.  its very hard to test, cause it's not consistent or reproducible.  it might help if it gave more info in the error about what it was doing.  The really odd thing is that the playback seems unaffected.  

The only other thing that crossed my mind is that this is occurring on my computer at work, and the firewall is set to a 15 minute TCP timeout.  However I don't think anything would be holding a single connection open for that long

**Comment by andocromn** [comment] 2017-04-20 18:00
I may have spoken too soon about the inconsistency.  yesterday and today, i got the message after putting on a long playlist... 50 tracks and it was about 2 minutes into the playback.  not sure if that tells you anything useful

**Comment by midwan** [comment] 2018-08-06 17:47
@andocromn 
I've just pushed v2.20: https://github.com/midwan/MB_SubSonic/releases/tag/v2.20

Please give it a try with this version and let me know if the problem persists?
I've added a new option to control if you want the Local Cache or not, or delete it as well. Try experimenting with that as well.

**Comment by maria95posteonet** [comment] 2018-08-16 17:08
Local cache GREAT idea - I have a remote Subsonic library and would like EVERYTHING except the actual audio file cached on the local PC where MusicBee is installed - metadata, thumbnails etc.

**Comment by maria95posteonet** [comment] 2018-08-21 11:03
During repeated attempted library scans I'm getting this error message like the guy above, server timeout basically:

Error retrieving response from Subsonic server:
System.Net.WebException: The operation timed out
at System.Net.HttpWebRequest.GetResponse()
at RestSharp.Http.GetRawResponse(HttpWebRequest request)
at RestSharp.Http.GetResponse(HttpWebRequest request)

I've turned everything else off on the NAS and it's fairly well-powered anyway to dedicate full resources to Subsonic while I set this up. I have a 100/100 line. 


Whenever I try to open Subsonic in Musicbee.

First it says "No access to /volume1/music" (I use Subsonic on a Synology NAS and that is the default music folder), then if I doubleclick on Subsonic again in the top heading it has expanded the node and to varying degrees starts reading and display library - I can click on folders and play files sometimes but it varies, and usually trying to browse to a new folder leads to the program hanging, with very large folders hanging indefinitely (3TB library total, 300.000 songs IIRC)

Sometimes it notes in the bottom status bar that it is successfully reading Subsonic file/folder/indexes whatever for a few hours, sometimes it stops with that error message above, if so the message has to be "OK"'ed for anything more to happen.

So I am left wondering - 

will, as I hope, basically the entire Subsonic database, ie. metadata, folder contents, images etc. except the actual audio files themselves eventually be cached locally by Musicbee ?

even though the folder/file scanning process has run pretty far for me (but I ran it overnight it's always stopped with an error msg in the morning) but never completed, is progress cached? Or does it start over again every time and needs to complete a full scan in one uninterrupted go in order to be operational?

is there anything I can do in Musicbee settings or otherwise to reduce the timeout error ? I think (and I have on my other Subsonic apps where there is a settings for this) a "server timeout" of 60 seconds - the NAS just needs it sometimes for whatever reason and with a longer timeout this error never appears

Other Subsonic apps e.g. Dsub Android work flawlessly atm

Thanks for a great program and any help you can offer!

**Comment by midwan** [comment] 2019-02-15 13:53
@maria95posteonet 
Sorry this took a while...

One of the available options in the plugin, is to "Cache server indexes" or not (it's a checkbox in the new settings window). This used to be always ON by default, but now you have the option to disable it.

Try testing with that option OFF, to see if it makes any difference? Basically it will not use any cached indexes, and will hit the server directly instead. If the problem is coming up during cache building this might solve it (and we'd know more about where to look).

**Comment by midwan** [comment] 2021-02-05 19:19
Please test with the latest release here: https://github.com/midwan/MB_SubSonic/releases/tag/v2.30
If there's still an issue on your side, feel free to post here, and we'll re-open the case.

**Closed by midwan** 2021-02-05 19:19 UTC
Labels: can't recreate
